package com.github.chrisvdalen.archunitgen.scanner

import com.intellij.openapi.project.Project
import com.intellij.psi.PsiClass
import com.intellij.psi.PsiJavaFile
import com.intellij.psi.search.GlobalSearchScope
import com.intellij.psi.search.searches.AllClassesSearch

/**
 * Heuristically identifies generated OpenAPI / Swagger code in the project.
 *
 * Detection strategy (any one hit is sufficient):
 *  1. Package contains an OpenAPI keyword (openapi, generated, swagger).
 *  2. The source file imports a `@Generated` annotation.
 *  3. The first 500 characters of the file contain a common generator comment.
 *
 * Deliberately conservative: ambiguous packages are NOT flagged unless a
 * second signal confirms generation.
 */
class OpenApiCodeDetector(private val project: Project) {

    companion object {
        private val GENERATED_ANNOTATION_FQNS = setOf(
            "javax.annotation.Generated",
            "jakarta.annotation.Generated",
        )

        private val OPENAPI_PACKAGE_KEYWORDS = listOf("openapi", "generated", "swagger")

        // Lowercase markers checked in the file header
        private val FILE_HEADER_MARKERS = listOf(
            "@generated",
            "do not edit",
            "generated by openapi",
            "openapi generator",
            "swagger codegen",
        )
    }

    fun detect(): OpenApiScanResult {
        val scope = GlobalSearchScope.projectScope(project)
        val generatedPackages = mutableSetOf<String>()
        val sampleClasses = mutableListOf<String>()

        AllClassesSearch.search(scope, project).findAll().forEach { psiClass ->
            val file = psiClass.containingFile as? PsiJavaFile ?: return@forEach
            if (isGeneratedCode(psiClass, file)) {
                generatedPackages.add(file.packageName)
                if (sampleClasses.size < 5) psiClass.qualifiedName?.let { sampleClasses.add(it) }
            }
        }

        return OpenApiScanResult(
            detectedPackages = generatedPackages,
            sampleClasses = sampleClasses,
            hasGeneratedCode = generatedPackages.isNotEmpty(),
        )
    }

    private fun isGeneratedCode(psiClass: PsiClass, file: PsiJavaFile): Boolean {
        val pkg = file.packageName

        // Signal 1: package keyword
        if (OPENAPI_PACKAGE_KEYWORDS.any { pkg.contains(it, ignoreCase = true) }) return true

        // Signal 2: @Generated import
        val imports = file.importList?.importStatements?.mapNotNull { it.qualifiedName } ?: emptyList()
        if (imports.any { it in GENERATED_ANNOTATION_FQNS }) return true

        // Signal 3: generator comment in file header (cheap text scan, no full AST walk)
        val header = file.text.take(500).lowercase()
        if (FILE_HEADER_MARKERS.any { header.contains(it) }) return true

        return false
    }
}

data class OpenApiScanResult(
    val detectedPackages: Set<String>,
    val sampleClasses: List<String>,
    val hasGeneratedCode: Boolean,
)
