package com.example.myapp.architecture;

// Generated by ArchUnit Rule Generator – review, adjust, and commit.
// Re-run the plugin to add or update rules.

import com.tngtech.archunit.junit.AnalyzeClasses;
import com.tngtech.archunit.junit.ArchTest;
import com.tngtech.archunit.lang.ArchRule;
import com.tngtech.archunit.lang.syntax.ArchRuleDefinition.classes;
import com.tngtech.archunit.lang.syntax.ArchRuleDefinition.noClasses;
import com.tngtech.archunit.library.Architectures.layeredArchitecture;
import org.springframework.stereotype.Controller;
import org.springframework.stereotype.Repository;
import org.springframework.stereotype.Service;
import org.springframework.web.bind.annotation.RestController;

@AnalyzeClasses(packages = "com.example.myapp")
class ArchitectureRulesTest {

    // Bypassing the service layer exposes persistence internals to the HTTP layer,
    // breaks encapsulation, and makes unit-testing controllers significantly harder.
    @ArchTest
    static final ArchRule controllers_should_not_depend_on_repositories =
        noClasses()
            .that().areAnnotatedWith(RestController.class)
            .or().areAnnotatedWith(Controller.class)
            .should().dependOnClassesThat().areAnnotatedWith(Repository.class)
            .because("Controllers must delegate to Services, not access Repositories directly");

    // Centralising all data-access calls in the service layer ensures business rules
    // are applied consistently before any persistence operation.
    @ArchTest
    static final ArchRule repositories_should_only_be_accessed_by_services =
        classes()
            .that().areAnnotatedWith(Repository.class)
            .should().onlyHaveDependentClassesThat()
            .areAnnotatedWith(Service.class)
            .orShould().onlyHaveDependentClassesThat().resideInAPackage("..test..")
            .because("Repositories must only be accessed from the service layer");

    // Coupling domain objects to Spring makes them impossible to use outside a Spring
    // context, hampers unit-testing, and conflates infrastructure concerns with business rules.
    @ArchTest
    static final ArchRule domain_classes_should_not_depend_on_spring =
        noClasses()
            .that().resideInAPackage("com.example.myapp.domain..")
            .should().dependOnClassesThat().resideInAPackage("org.springframework..")
            .because("Domain classes must be framework-agnostic");

    // Generated code regenerates with every OpenAPI spec change. Domain classes that
    // depend on generated types become fragile and couple the persistence model to the API contract.
    @ArchTest
    static final ArchRule generated_openapi_classes_should_not_leak_into_domain =
        noClasses()
            .that().resideInAPackage("com.example.myapp.domain..")
            .should().dependOnClassesThat().resideInAPackage("com.example.myapp.generated..")
            .because("Generated OpenAPI types must not pollute the domain layer");

    // Explicit layer rules prevent architectural drift. Once encoded, any violation
    // becomes a test failure, not a code-review comment.
    @ArchTest
    static final ArchRule layered_architecture_should_be_respected =
        layeredArchitecture().consideringAllDependencies()
            .layer("Controller").definedBy("com.example.myapp.web..")
            .layer("Service").definedBy("com.example.myapp.service..")
            .layer("Repository").definedBy("com.example.myapp.repository..")
            .layer("Domain").definedBy("com.example.myapp.domain..")
            .whereLayer("Controller").mayNotBeAccessedByAnyLayer()
            .whereLayer("Repository").mayOnlyBeAccessedByLayers("Service")
            .whereLayer("Domain").mayOnlyBeAccessedByLayers("Service", "Repository");

    // DTOs are API-layer types and must not pollute the domain model.
    @ArchTest
    static final ArchRule dto_classes_should_not_reside_in_domain =
        noClasses()
            .that().resideInAPackage("com.example.myapp.dto..")
            .should().resideInAPackage("com.example.myapp.domain..")
            .because("DTOs are API-layer types and must not pollute the domain model");

}
