package com.github.chrisvdalen.archunitgen.generator

import com.github.chrisvdalen.archunitgen.config.PluginConfig
import com.github.chrisvdalen.archunitgen.model.RuleStatus
import com.github.chrisvdalen.archunitgen.model.RuleSuggestion

/**
 * Renders a list of accepted [RuleSuggestion] objects into a compilable Java 21 test class.
 *
 * The output intentionally mirrors what a senior developer would write by hand:
 *  - Static final ArchRule fields (ArchUnit's recommended style for JUnit 5)
 *  - A short comment above each rule (why it exists, not what it does)
 *  - Alphabetically sorted imports
 *  - No wildcard imports
 */
class ArchUnitTestGenerator {

    fun generate(
        suggestions: List<RuleSuggestion>,
        config: PluginConfig,
        basePackage: String,
    ): GeneratedTestFile {
        val accepted = suggestions.filter { it.status == RuleStatus.ACCEPTED }

        val testPackage = resolveTestPackage(basePackage, config.testOutputPackage)
        val className = config.testClassName
        val allImports = collectImports(accepted)
        val methods = accepted.map { renderField(it) }

        val code = buildString {
            appendLine("package $testPackage;")
            appendLine()
            appendLine("// Generated by ArchUnit Rule Generator – review, adjust, and commit.")
            appendLine("// Re-run the plugin to add or update rules.")
            appendLine()
            allImports.sorted().forEach { appendLine("import $it;") }
            appendLine()
            appendLine("@AnalyzeClasses(packages = \"$basePackage\")")
            appendLine("class $className {")
            appendLine()
            methods.forEach { append(it) }
            appendLine("}")
        }

        return GeneratedTestFile(
            packageName = testPackage,
            className = className,
            code = code,
            relativePath = "src/test/java/${testPackage.replace('.', '/')}/$className.java",
        )
    }

    // ── Private helpers ───────────────────────────────────────────────────────

    private fun resolveTestPackage(basePackage: String, configuredSuffix: String): String =
        if (configuredSuffix.startsWith(basePackage)) configuredSuffix
        else if (basePackage.isBlank()) configuredSuffix
        else "$basePackage.$configuredSuffix"

    private fun collectImports(suggestions: List<RuleSuggestion>): Set<String> =
        suggestions.flatMap { it.ruleTemplate.imports }.toSet() +
            setOf(
                "com.tngtech.archunit.junit.AnalyzeClasses",
                "com.tngtech.archunit.junit.ArchTest",
                "com.tngtech.archunit.lang.ArchRule",
            )

    private fun renderField(s: RuleSuggestion): String = buildString {
        appendLine("    // ${s.rationale}")
        appendLine("    @ArchTest")
        appendLine("    static final ArchRule ${s.ruleTemplate.methodName} =")
        s.ruleTemplate.codeLines.forEachIndexed { idx, line ->
            val isLast = idx == s.ruleTemplate.codeLines.lastIndex
            if (isLast) appendLine("        $line;") else appendLine("        $line")
        }
        appendLine()
    }
}

data class GeneratedTestFile(
    val packageName: String,
    val className: String,
    val code: String,
    /** Relative path from project root, e.g. `src/test/java/com/example/architecture/ArchitectureRulesTest.java` */
    val relativePath: String,
)
